import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { ExternalLink } from 'lucide-react';
import { partners } from '@/data/partners';
import SectionHeading from '@/components/ui/SectionHeading';
import ScrollReveal from '@/components/ui/ScrollReveal';
import Button from '@/components/ui/Button';
export default function Partners() {
    return (_jsx("section", { className: "relative py-20 md:py-28 lg:py-32 border-section", children: _jsxs("div", { className: "container-max section-padding", children: [_jsx(SectionHeading, { eyebrow: "Partners & Collaborators", title: "Built together.", subtitle: "Great technology is rarely built alone. Cloudforge works with developers, designers, creatives, businesses and technology partners to bring projects to life." }), _jsx("div", { className: "mt-16 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6", children: partners.map((partner, i) => (_jsxs(ScrollReveal, { stagger: (i % 4) + 1, as: "article", className: "group glass-card glass-hover rounded-2xl p-8 text-center", children: [_jsx("div", { className: "w-16 h-16 mx-auto rounded-2xl bg-accent-500/10 border border-accent-500/20 flex items-center justify-center mb-5 transition-colors duration-300 group-hover:bg-accent-500/20", children: _jsx("span", { className: "font-display font-bold text-xl text-accent-600", children: partner.name.charAt(0) }) }), _jsx("h3", { className: "text-base font-semibold text-light-text mb-1", children: partner.name }), _jsx("p", { className: "text-sm text-light-muted mb-4", children: partner.role }), _jsxs("a", { href: partner.link, target: "_blank", rel: "noopener noreferrer", className: "inline-flex items-center gap-1.5 text-xs font-medium text-accent-600 hover:text-accent-700 transition-colors", children: ["Visit Site", _jsx(ExternalLink, { size: 12 })] })] }, partner.id))) }), _jsx("div", { className: "mt-12 text-center", children: _jsx(Button, { to: "/partners", variant: "outline", size: "md", children: "Become a Partner" }) })] }) }));
}
