import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { ArrowRight } from 'lucide-react';
import { Link } from 'react-router-dom';
import { ongoingProjects } from '@/data/projects';
import SEO from '@/components/ui/SEO';
import PageHeader from '@/components/ui/PageHeader';
export default function OngoingProjectsPage() {
    return (_jsxs(_Fragment, { children: [_jsx(SEO, { title: "Ongoing Projects \u2014 Cloudforge", description: "Projects currently in development at Cloudforge." }), _jsx(PageHeader, { eyebrow: "Ongoing Projects", title: "Currently in progress.", subtitle: "Follow the products we are actively designing and building." }), _jsx("section", { className: "pb-24 pt-8", children: _jsx("div", { className: "container-max section-padding grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6", children: ongoingProjects.map((project) => (_jsxs(Link, { to: `/projects/${project.slug}`, className: "group glass-card rounded-2xl p-6 hover:-translate-y-1 transition-transform", children: [_jsxs("div", { className: "flex items-start justify-between gap-4", children: [_jsx("h2", { className: "text-xl font-semibold text-light-text group-hover:text-accent-600", children: project.name }), _jsxs("span", { className: "px-2.5 py-1 text-xs rounded-full bg-accent-500/10 text-accent-600", children: [project.progress, "%"] })] }), _jsx("p", { className: "mt-4 text-sm text-light-muted leading-relaxed", children: project.description }), _jsx("p", { className: "mt-6 text-xs font-medium text-accent-600", children: project.status }), _jsx("div", { className: "mt-3 h-2 rounded-full bg-black/[0.06] overflow-hidden", children: _jsx("div", { className: "h-full rounded-full bg-accent-600", style: { width: `${project.progress}%` } }) }), _jsx("div", { className: "mt-5 flex flex-wrap gap-2", children: project.technologies.map((technology) => _jsx("span", { className: "px-2.5 py-1 text-xs rounded-md bg-black/[0.04] text-light-muted border border-light-border", children: technology }, technology)) }), _jsxs("span", { className: "mt-6 inline-flex items-center gap-1.5 text-sm font-medium text-accent-600", children: ["View Project Details ", _jsx(ArrowRight, { size: 14 })] })] }, project.slug))) }) })] }));
}
