import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { ExternalLink, Handshake } from 'lucide-react';
import { partners } from '@/data/partners';
import SEO from '@/components/ui/SEO';
import PageHeader from '@/components/ui/PageHeader';
import ScrollReveal from '@/components/ui/ScrollReveal';
import Button from '@/components/ui/Button';
import CTASection from '@/components/sections/CTASection';
export default function PartnersPage() {
    return (_jsxs(_Fragment, { children: [_jsx(SEO, { title: "Partners & Collaborators \u2014 Cloudforge", description: "Great technology is rarely built alone. Cloudforge works with developers, designers, creatives and technology partners." }), _jsx(PageHeader, { eyebrow: "Partners & Collaborators", title: "Built together.", subtitle: "Great technology is rarely built alone. Cloudforge works with developers, designers, creatives, businesses and technology partners to bring projects to life." }), _jsx("section", { className: "pb-16 pt-4", children: _jsx("div", { className: "container-max section-padding", children: _jsx("div", { className: "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6", children: partners.map((partner, i) => (_jsxs(ScrollReveal, { stagger: (i % 4) + 1, as: "article", className: "group glass-card glass-hover rounded-2xl p-8 text-center", children: [_jsx("div", { className: "w-16 h-16 mx-auto rounded-2xl bg-accent-500/10 border border-accent-500/20 flex items-center justify-center mb-5 transition-colors duration-300 group-hover:bg-accent-500/20", children: _jsx("span", { className: "font-display font-bold text-xl text-accent-600", children: partner.name.charAt(0) }) }), _jsx("h3", { className: "text-base font-semibold text-light-text mb-1", children: partner.name }), _jsx("p", { className: "text-sm text-light-muted mb-4", children: partner.role }), _jsxs("a", { href: partner.link, target: "_blank", rel: "noopener noreferrer", className: "inline-flex items-center gap-1.5 text-xs font-medium text-accent-600 hover:text-accent-700 transition-colors", children: ["Visit Site", _jsx(ExternalLink, { size: 12 })] })] }, partner.id))) }) }) }), _jsx("section", { className: "py-12 md:py-16", children: _jsx("div", { className: "container-max section-padding", children: _jsxs(ScrollReveal, { className: "glass-card rounded-3xl p-12 md:p-16 text-center max-w-3xl mx-auto", children: [_jsx("div", { className: "w-14 h-14 mx-auto rounded-2xl bg-accent-500/10 border border-accent-500/20 flex items-center justify-center mb-6", children: _jsx(Handshake, { size: 28, className: "text-accent-600" }) }), _jsx("h2", { className: "text-2xl sm:text-3xl font-bold text-light-text mb-4", children: "Want to partner with Cloudforge?" }), _jsx("p", { className: "text-light-muted leading-relaxed mb-8", children: "We\u2019re always looking to collaborate with talented developers, designers and technology partners. Let\u2019s build something great together." }), _jsx(Button, { to: "/contact", size: "lg", children: "Get in Touch" })] }) }) }), _jsx(CTASection, {})] }));
}
