import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight } from 'lucide-react';
import { projects, projectCategories } from '@/data/projects';
import SEO from '@/components/ui/SEO';
import PageHeader from '@/components/ui/PageHeader';
import ScrollReveal from '@/components/ui/ScrollReveal';
import CTASection from '@/components/sections/CTASection';
export default function ProjectsPage() {
    const [activeCategory, setActiveCategory] = useState('All');
    const filtered = activeCategory === 'All'
        ? projects
        : projects.filter((p) => p.category === activeCategory);
    return (_jsxs(_Fragment, { children: [_jsx(SEO, { title: "Projects \u2014 Cloudforge", description: "Explore digital products and experiences built by Cloudforge, including e-commerce platforms, AI tools and SaaS applications." }), _jsx(PageHeader, { eyebrow: "Our Work", title: "Built with purpose.", subtitle: "A look at some of the digital products and experiences we\\u2019ve created." }), _jsx("div", { className: "container-max section-padding pt-4", children: _jsx("div", { className: "flex flex-wrap justify-center gap-3", children: projectCategories.map((cat) => (_jsx("button", { onClick: () => setActiveCategory(cat), className: `px-5 py-2.5 text-sm font-medium rounded-full transition-all duration-300 ${activeCategory === cat
                            ? 'bg-accent-600 text-white'
                            : 'glass text-light-muted hover:text-light-text'}`, children: cat }, cat))) }) }), _jsx("section", { className: "pb-16 pt-8", children: _jsx("div", { className: "container-max section-padding", children: _jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6", children: filtered.map((project, i) => (_jsx(ScrollReveal, { stagger: (i % 3) + 1, as: "article", className: "group glass-card rounded-2xl overflow-hidden hover:shadow-xl hover:shadow-accent-600/5 transition-all duration-300 hover:-translate-y-1", children: _jsxs(Link, { to: `/projects/${project.slug}`, className: "block", children: [_jsxs("div", { className: "relative h-56 overflow-hidden", children: [_jsx("img", { src: project.image, alt: project.name, loading: "lazy", className: "w-full h-full object-cover transition-transform duration-700 group-hover:scale-110" }), _jsx("div", { className: "absolute inset-0 bg-gradient-to-t from-light-surface/80 via-transparent to-transparent" }), _jsx("div", { className: "absolute top-4 left-4", children: _jsx("span", { className: "px-3 py-1.5 text-xs font-mono rounded-full glass text-accent-600", children: project.category }) })] }), _jsxs("div", { className: "p-6", children: [_jsx("h3", { className: "text-lg font-semibold text-light-text mb-2 group-hover:text-accent-600 transition-colors", children: project.name }), _jsx("p", { className: "text-sm text-light-muted leading-relaxed mb-4", children: project.shortDescription }), _jsx("div", { className: "flex flex-wrap gap-2 mb-5", children: project.technologies.slice(0, 3).map((tech) => (_jsx("span", { className: "px-2.5 py-1 text-xs rounded-md bg-black/[0.04] text-light-muted border border-light-border", children: tech }, tech))) }), _jsxs("div", { className: "inline-flex items-center gap-1.5 text-sm font-medium text-accent-600 group-hover:text-accent-700 transition-colors", children: ["View Case Study", _jsx(ArrowRight, { size: 14, className: "transition-transform group-hover:translate-x-1" })] })] })] }) }, project.slug))) }) }) }), _jsx(CTASection, {})] }));
}
