import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Check, ArrowRight } from 'lucide-react';
import { services } from '@/data/services';
import SEO from '@/components/ui/SEO';
import PageHeader from '@/components/ui/PageHeader';
import ScrollReveal from '@/components/ui/ScrollReveal';
import Button from '@/components/ui/Button';
import CTASection from '@/components/sections/CTASection';
export default function ServicesPage() {
    return (_jsxs(_Fragment, { children: [_jsx(SEO, { title: "Services \u2014 Cloudforge", description: "Web development, e-commerce, custom software, business automation, UI/UX design and digital transformation services." }), _jsx(PageHeader, { eyebrow: "Our Services", title: "Technology that moves your business forward.", subtitle: "We provide practical digital solutions designed to solve real business problems \u2014 not just build attractive interfaces." }), _jsx("section", { className: "pb-16 pt-4", children: _jsx("div", { className: "container-max section-padding space-y-10", children: services.map((service, i) => {
                        const Icon = service.icon;
                        const reversed = i % 2 === 1;
                        return (_jsxs(ScrollReveal, { as: "article", className: `grid grid-cols-1 lg:grid-cols-2 gap-12 items-center ${reversed ? 'lg:[direction:rtl]' : ''}`, children: [_jsxs("div", { className: "lg:[direction:ltr]", children: [_jsx("div", { className: "w-14 h-14 rounded-2xl bg-accent-500/10 border border-accent-500/20 flex items-center justify-center mb-6", children: _jsx(Icon, { size: 28, className: "text-accent-600" }) }), _jsx("h3", { className: "text-2xl sm:text-3xl font-bold text-light-text mb-4", children: service.title }), _jsx("p", { className: "text-light-muted leading-relaxed mb-6", children: service.description }), _jsx("ul", { className: "space-y-3", children: service.features.map((feature) => (_jsxs("li", { className: "flex items-center gap-3", children: [_jsx("div", { className: "w-5 h-5 rounded-full bg-accent-500/10 flex items-center justify-center shrink-0", children: _jsx(Check, { size: 12, className: "text-accent-600" }) }), _jsx("span", { className: "text-sm text-light-text", children: feature })] }, feature))) }), _jsx("div", { className: "mt-8", children: _jsxs(Button, { to: "/contact", variant: "outline", size: "md", children: ["Start a Project", _jsx(ArrowRight, { size: 16 })] }) })] }), _jsx("div", { className: "lg:[direction:ltr]", children: _jsxs("div", { className: "glass-card rounded-2xl h-full min-h-[300px] flex items-center justify-center relative overflow-hidden", children: [service.image ? (_jsx("img", { src: service.image, alt: `${service.title} project preview`, loading: "lazy", className: "absolute inset-0 w-full h-full object-cover" })) : (_jsxs(_Fragment, { children: [_jsx("div", { className: "absolute top-0 right-0 w-40 h-40 bg-accent-400/5 rounded-full blur-[60px]" }), _jsx(Icon, { size: 80, className: "text-accent-500/20" })] })), _jsx("div", { className: "absolute inset-0 bg-gradient-to-t from-light-surface/30 to-transparent" })] }) })] }, service.id));
                    }) }) }), _jsx(CTASection, {})] }));
}
