import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useParams, Link, Navigate } from 'react-router-dom';
import { ArrowLeft, ExternalLink, Github, Linkedin, Twitter } from 'lucide-react';
import { teamMembers } from '@/data/team';
import SEO from '@/components/ui/SEO';
export default function TeamMemberPage() {
    const { id } = useParams();
    const member = teamMembers.find((teamMember) => teamMember.id === id);
    if (!member)
        return _jsx(Navigate, { to: "/about", replace: true });
    return (_jsxs(_Fragment, { children: [_jsx(SEO, { title: `${member.name} — Cloudforge`, description: `${member.name}'s profile and portfolio at Cloudforge.` }), _jsx("section", { className: "relative pt-24 pb-16 overflow-hidden", children: _jsxs("div", { className: "container-max section-padding", children: [_jsxs(Link, { to: "/about", className: "inline-flex items-center gap-2 text-sm text-light-muted hover:text-light-text transition-colors mb-10", children: [_jsx(ArrowLeft, { size: 16 }), " Back to Team"] }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-[240px_1fr] gap-10 items-center", children: [_jsx("img", { src: member.image, alt: member.name, className: "w-56 h-56 rounded-2xl object-cover glass-card" }), _jsxs("div", { children: [_jsx("p", { className: "text-sm font-medium text-accent-600 mb-3", children: member.role }), _jsx("h1", { className: "text-4xl sm:text-5xl font-bold tracking-tight text-light-text", children: member.name }), _jsx("p", { className: "mt-5 max-w-2xl text-lg text-light-muted leading-relaxed", children: member.bio }), _jsxs("div", { className: "mt-6 flex gap-3", children: [member.socials.linkedin && _jsx("a", { href: member.socials.linkedin, "aria-label": "LinkedIn", className: "text-light-muted hover:text-accent-600", children: _jsx(Linkedin, { size: 18 }) }), member.socials.twitter && _jsx("a", { href: member.socials.twitter, "aria-label": "Twitter", className: "text-light-muted hover:text-accent-600", children: _jsx(Twitter, { size: 18 }) }), member.socials.github && _jsx("a", { href: member.socials.github, "aria-label": "GitHub", className: "text-light-muted hover:text-accent-600", children: _jsx(Github, { size: 18 }) })] }), member.portfolioUrl && (_jsxs("a", { href: member.portfolioUrl, target: "_blank", rel: "noopener noreferrer", className: "mt-6 inline-flex items-center gap-2 rounded-lg bg-accent-600 px-4 py-2.5 text-sm font-medium text-white hover:bg-accent-700 transition-colors", children: ["Visit Personal Portfolio", _jsx(ExternalLink, { size: 15 })] }))] })] })] }) })] }));
}
